
import Head from 'next/head'
import { Auth } from './auth_component'
import { FooterComponent } from './footer_component'
import HeaderComponent from './header_component'
import Script from 'next/script'


const Home = () => {
  return (
    <div>
       <Head>
          <title>BitHelper System</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://kit.fontawesome.com/0c3743f477.js" crossOrigin="anonymous"></script>
        </Head>
      <div className="section">
       <Script src="https://third-party-script.js"></Script>
        <div className='view' >  
          < HeaderComponent />
          < Auth/>
          < FooterComponent/>
        </div>
      </div>
     
    </div>
   
  )
}

export default Home
